### ISSUE TITLE
No consecutive numbering of single line equations

### ISSUE THREAD

**Issue by chrisschuerz** [nuest/rticles#1]
Single line equations written as:
```
$$
y = x^2
$$
```
are translated to:
```
\[
y = x^2
\]
```
in the .tex document.
For a correct enumeration in the final .pdf document however, the translation must be:
```
\begin{equation}
y = x^2
\end{equation}
```
A manual change in the .tex document and the knitting of the the corrected document fixes the problem. Nevertheless, an automized version is most likely preferable :grin:

**Comment by nuest** [comment]
AFAICS the use of `$$` in Rmd files has the advantage of having previews in RStudio and handling different output formats (HTML, PDF).

There seem to be options to automatically number equations based on `$$`:

- https://tex.stackexchange.com/questions/111868/pandoc-how-can-i-get-numbered-latex-equations-to-show-up-in-both-pdf-and-html-o
- https://github.com/tomduck/pandoc-eqnos#installation
- https://github.com/lierdakil/pandoc-crossref

**But** they all require to install some system library, which I would not prefer to do. Instead I would document in the template that authors must use `\begin{equation}`. This is also in line with the other templates.

**Comment by chrisschuerz** [comment]
Yes I agree that the with the advantages the ```$$``` has in Rmarkdown. If the user wants to use the template solely for compiling the file to submit the use of ```\begin{equation} ... \end{equation}``` is "tolerable". 
Thank you for providing the comment in the template file!
